[package]
name = "client_pool"
version = "0.1.0"
edition = "2021"

[[example]]
name = "client_pool"
path = "client_pool.rs"

[dependencies]
futures = "0.3.27"
tokio-stream = "0.1.11"
lychee-lib = { path = "../../lychee-lib", version = "0.10.1" }
tokio = { version = "1.24.2", features = ["full"] }
